import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";
import { SectionMarquee } from "@/components/Layout/SectionMarquee";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const ppNeueBold = localFont({
  src: "./fonts/pp-neue-montreal/ppneuemontreal-bold.woff",
  variable: "--font-neue-bold",
  weight: "700",
});

const ppNeueMed= localFont({
  src: "./fonts/pp-neue-montreal/ppneuemontreal-medium.woff",
  variable: "--font-neue-med",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ppNeueBold.variable} ${ppNeueMed.variable} antialiased mx-auto`}
      >
        <Header />
        {children}
        <SectionMarquee />
        <Footer />
      </body>
    </html>
  );
}
